### ISSUE TITLE
Custom metadata for attributes

### ISSUE THREAD

**Issue by smcgivern** [rightscale/attributor#113]
Sean McGivern [5:08 PM] 
> I'd like to add a custom option to attributes of any type (in this case, it's whether the attribute is loggable)
> it doesn't look like attributor supports any kind of custom metadata like this; is it something we'd like to add?

Josep Blanquer [6:01 PM] 
> ya, it doesn't have it right now, and yes, it is something we'd like to add
> it'd be a well known option...something like... :metadata ... or :custom_data ...
> which is a hash...it wouldn't be validated or understood....
> but will allow you to add things in it
> and at runtime would be retrievable through options[:custom_data] ...
> and will also exist in the generated JSON docs
> so anybody that knows how to interpret that would be able to

**Comment by blanquer** [comment]
closed by #114
