### ISSUE TITLE
Provide native_type for Attributor::Boolean

### ISSUE THREAD

**Issue by justingaylor** [rightscale/attributor#31]
Per discussion here: https://github.com/rightscale/attributor/pull/16/files#r6722390

It should be possible to make ```TrueClass``` and ```FalseClass``` both have a common ancestor and implement ```Attributor::Boolean.native_type```, provided that the following points are observed:
- The parent class of ```TrueClass``` and ```FalseClass``` needs to be in the ```Attributor``` namespace somewhere.
- We cannot mix anything into the classes other than logic to report that ```TrueClass``` and ```FalseClass``` are ```Attributor::Boolean``` objects.
- Also confirm that ```===``` works.

For Inspiration:
https://github.com/mongoid/mongoid/blob/master/lib/mongoid/extensions/boolean.rb
https://github.com/mongoid/mongoid/blob/master/lib/mongoid/extensions/false_class.rb
https://github.com/mongoid/mongoid/blob/master/lib/mongoid/extensions/true_class.rb

**Comment by careo** [comment]
We added `valid_type?` for cases like this where we really mean to use the `something == type.native_type` value to determine if `something` is a a valid instance of the `type`.
