### ISSUE TITLE
Attributor::Hash should implement fully the interface of Ruby's Hash

### ISSUE THREAD

**Issue by justingaylor** [rightscale/attributor#76]
Currently, the Attributor::Hash returned when loading an attribute of type Attributor::Hash doesn't quack like a Ruby Hash.

```
[2] pry(main)> config.has_key?('foobar')
NoMethodError: undefined method `has_key?' for #<Attributor::Hash:0x007fb6e008cd90>
from (pry):2:in `block (2 levels) in <top (required)>
```

We should fix this.

**Comment by careo** [comment]
`has_key?` has been added, along with a number of other methods.
