### ISSUE TITLE
Attributor throws syntax error when a header is defined with hypens

### ISSUE THREAD

**Issue by nitinmohan87** [rightscale/attributor#78]
As a user, I should be able to define headers with hyphens in the name like "Content-Type", "X-Api-Version", etc.

But attributor throws a `Syntax Error` if I try to define a header with hyphens.
```
headers do
  header :'X-Api-Version', String, values: ['1.0'], required: true
end

SyntaxError: .../ruby/2.1.2/lib/ruby/gems/2.1.0/gems/attributor-2.1.0/lib/attributor/types/model.rb:38: syntax error, unexpected '-', expecting ';' or '\n'
        def X-API-VERSION
```

The attributor should be able to catch such exceptions.

**Comment by careo** [comment]
The headers in praxis default to using hashes now, so this should be fixed.
