### ISSUE TITLE
Attributor::String.load() loads Arrays and other complex types

### ISSUE THREAD

**Issue by justingaylor** [rightscale/attributor#97]
For example:
```
$ bundle exec irb
irb(main):001:0> require 'attributor'
=> true
irb(main):002:0> Attributor::String.load([1,2,3])
=> "[1, 2, 3]"
```

Underneath, I see that the Attributor::String type does `String(value)`, but in this case, it doesn't seem intuitive what should be done when a complex type like an Array or Hash are passed in.

In my particular case, a YAML file was incorrectly specifying a String value as an Array, then when trying to load it we were suddenly getting array brackets around the expected string. It would have been preferable in this case to receive an Attributor error saying that Array in not a valid String.

**Comment by careo** [comment]
Fixed in 2.4.0.
